name: Ejecutar y Exportar Notebook

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 23 * * *' # 19:00 Bolivia (UTC-4)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Bajar el código del repositorio
    - name: Checkout repo
      uses: actions/checkout@v3

    # 2. Instalar Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # 3. Instalar dependencias
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./p_web_ts/requirements.txt

    # 4. Instalar Quarto
    - name: Install Quarto
      uses: quarto-dev/quarto-actions/setup@v2

    # 5. Ejecutar el notebook y generar HTML crudo
    - name: Execute and Export Notebook
      uses: nick-fields/retry@v3
      with:
        timeout_minutes: 10
        max_attempts: 3
        retry_wait_seconds: 300
        command: jupyter nbconvert --to html --execute ./p_web_ts/p_web_ts_api.ipynb --output p_web_ts_api.html

    # 6. Renderizar el sitio completo con Quarto (aplica el estilo)
    - name: Render Quarto site
      run: quarto render

    # 7. Commit y push de los cambios
    - name: Commit and Push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

        git add .
        git commit -m "Update site with latest notebook execution [skip ci]" || echo "No hay cambios"
        git push
